document: feedback-pipeline-workload
version: 1
data:
  name: JMC
  description: JDK Mission Control application and libraries
  maintainer: sst_java
  
  packages: []

  arch_packages:
    x86_64:
    - jmc
    - jmc-core
  labels:
  - eln
